# azure-pipelines.yml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SOURCE_RELEASE: 'ChemCompoundDB:main'
  NEW_RELEASE_BASE_NAME: 'ChemCompoundDB'

stages:
  - stage: FortifyScan
    displayName: 'Fortify SAST Scan & Policy Check'
    jobs:
      - job: RunFortifyScan
        displayName: 'Create Release, Scan and Check Policy'
        container:
          image: fortifydocker/fortify-ci-tools:latest-jdk-17

        variables:
          FCLI_DEFAULT_FOD_USER: $(FOD_USER)
          FCLI_DEFAULT_FOD_PASSWORD: $(FOD_PASSWORD)
          FCLI_DEFAULT_FOD_TENANT: $(FOD_TENANT)
          FCLI_DEFAULT_FOD_URL: $(FOD_URL)
          DYNAMIC_RELEASE_NAME: '$(NEW_RELEASE_BASE_NAME):build-$(Build.BuildId)'

        steps:
          - checkout: self

          - script: fcli fod session login -u $(FOD_USER) -p $(FOD_PASSWORD) -t $(FOD_TENANT) --url $(FOD_URL)
            displayName: '1. Login to Fortify on Demand'

          - script: fcli fod release create $(DYNAMIC_RELEASE_NAME) --status Development --store=releaseId
            displayName: '2. Create new Release: $(DYNAMIC_RELEASE_NAME)'

          - script: scancentral package -bt mvn -oss -o package.zip
            workingDirectory: $(Build.SourcesDirectory)
            displayName: '3. Package application source code'

          - script: |
              fcli fod sast start --release ::releaseId:: --file package.zip --store=Id
              fcli fod sast wait-for ::Id:: --interval=30s
            workingDirectory: $(Build.SourcesDirectory)
            displayName: '4. Start SAST Scan and wait for completion'

          - script: |
              # echo "--- Checking Policy ---"
              # fcli fod action run check-policy --release ::releaseId::
              
              echo "--- Listing Issues ---"
              fcli fod issue list --release ::releaseId::
              
              echo "--- Generating Release Summary ---"
              fcli fod action run release-summary --release ::releaseId::
            displayName: '5. Check Policy and Generate Reports'

          - script: fcli fod session logout
            displayName: '6. Logout from Fortify on Demand'
            condition: always()
