trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: FortifyScan
  displayName: 'Fortify SAST Security Scan'
  jobs:
  - job: RunFortifyScan
    displayName: 'Run Fortify SAST Scan'
    container:
      image: fortifydocker/fortify-ci-tools:latest-jdk-17
    
    variables:
      FCLI_DEFAULT_FOD_USER: $(FOD_USER)
      FCLI_DEFAULT_FOD_PASSWORD: $(FOD_PASSWORD)
      FCLI_DEFAULT_FOD_TENANT: $(FOD_TENANT)
      FCLI_DEFAULT_FOD_URL: $(FOD_URL)

      NOTES_FOR_FOD: 'Triggered by ADO Pipeline $(Build.BuildId): $(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)'

    steps:
      - script: fcli --version
        displayName: '1. Login to Fortify on Demand'

      - script: scancentral package -bt mvn -oss -o package.zip
        displayName: '2. Package application source code with scancentral'
      
      - script: fcli fod action run package
        displayName: '3. Package application source code with fod action'